# Generated by Django 4.2.30 on 2026-09-12 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('generations_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='garments/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('owner_phone', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_generation', models.DecimalField(decimal_places=2, default=6.0, max_digits=6)),
                ('free_trials_per_customer', models.PositiveIntegerField(default=2)),
                ('charge_customer_per_generation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TryOnJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_image', models.ImageField(upload_to='tryon/person/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='tryon/result/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('cost_charged_to_shop', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_jobs', to='core.enduser')),
                ('garment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.garment')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_jobs', to='core.shop')),
            ],
        ),
        migrations.AddField(
            model_name='garment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='core.shop'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='core.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='enduser',
            unique_together={('shop', 'session_key')},
        ),
    ]
