# Generated by Django 4.2.30 on 2026-09-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shop_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image_generation_method',
            field=models.CharField(choices=[('fashn', 'Fashn'), ('mock', 'Mock'), ('gemini', 'Gemini Nano Banana')], default='fashn', max_length=20),
        ),
    ]
