# Generated by Django 4.2.30 on 2026-09-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shop_image_generation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image_generation_method',
            field=models.CharField(choices=[('fashn', 'Fashn'), ('mock', 'Mock'), ('gemini', 'Gemini Nano Banana'), ('idm_vton', 'IDM-VTON (Gradio)')], default='fashn', max_length=20),
        ),
    ]
