# Generated by Django 4.2.30 on 2026-09-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shop_image_generation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='image2',
            field=models.ImageField(blank=True, help_text='Optional second image of the garment', null=True, upload_to='garments/'),
        ),
        migrations.AddField(
            model_name='garment',
            name='prompt',
            field=models.TextField(blank=True, help_text='Custom prompt instructions for Gemini', null=True),
        ),
        migrations.AlterField(
            model_name='garment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image_generation_method',
            field=models.CharField(choices=[('fashn', 'Fashn'), ('mock', 'Mock'), ('gemini', 'Gemini Nano Banana'), ('gemini', 'Gemini Nano Banana (API)'), ('gemini_playwright', 'Gemini (Playwright Automation)'), ('idm_vton', 'IDM-VTON (Gradio)')], default='fashn', max_length=20),
        ),
    ]
