# Generated by Django 4.2.30 on 2026-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_garment_image2_garment_prompt_alter_garment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='size_measurements',
            field=models.JSONField(blank=True, default=dict, help_text='Dict mapping sizes to dict of measurements (chest, shoulder, length)'),
        ),
        migrations.AddField(
            model_name='garment',
            name='sizes_available',
            field=models.JSONField(blank=True, default=list, help_text='List of sizes available (S, M, L, XL)'),
        ),
    ]
