# Generated by Django 4.2.30 on 2026-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_garment_size_measurements_garment_sizes_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonjob',
            name='selected_size',
            field=models.CharField(blank=True, help_text='The size the user chose to try on', max_length=10),
        ),
        migrations.AddField(
            model_name='tryonjob',
            name='user_measurements',
            field=models.JSONField(blank=True, default=dict, help_text="The user's estimated or actual measurements at time of generation"),
        ),
    ]
